name: Deploy to Server

on:
  push:
    branches:
      - main  # 可以根据实际情况修改触发条件

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no -p 22 root@${{ secrets.DEPLOYMENT_SERVER }} 'cd /root/projects/MyNote-backend && git pull'
